package permission

// Catalogue is the canonical set of permission keys the API exposes today.
var Catalogue = []Permission{
	{Key: "ci:read", Resource: "ci", Action: "read", Description: "Read configuration items"},
	{Key: "ci:write", Resource: "ci", Action: "write", Description: "Create and update configuration items"},
	{Key: "ci:delete", Resource: "ci", Action: "delete", Description: "Delete configuration items"},
	{Key: "topology:read", Resource: "topology", Action: "read", Description: "Read CI topology graphs"},
	{Key: "discovery:read", Resource: "discovery", Action: "read", Description: "Read collectors and discovery jobs"},
	{Key: "discovery:write", Resource: "discovery", Action: "write", Description: "Manage discovery jobs and imports"},
	{Key: "asset:read", Resource: "asset", Action: "read", Description: "Read assets"},
	{Key: "asset:write", Resource: "asset", Action: "write", Description: "Manage assets"},
	{Key: "assignment:read", Resource: "assignment", Action: "read", Description: "Read assignments"},
	{Key: "assignment:write", Resource: "assignment", Action: "write", Description: "Manage assignments"},
	{Key: "document:read", Resource: "document", Action: "read", Description: "Read documents"},
	{Key: "document:write", Resource: "document", Action: "write", Description: "Manage documents"},
	{Key: "stocktake:read", Resource: "stocktake", Action: "read", Description: "Read stocktakes"},
	{Key: "stocktake:write", Resource: "stocktake", Action: "write", Description: "Manage stocktakes"},
	{Key: "ticket:read", Resource: "ticket", Action: "read", Description: "Read tickets"},
	{Key: "ticket:write", Resource: "ticket", Action: "write", Description: "Manage tickets and comments"},
	{Key: "user:read", Resource: "user", Action: "read", Description: "Read users and teams"},
	{Key: "user:write", Resource: "user", Action: "write", Description: "Manage users and teams"},
	{Key: "role:read", Resource: "role", Action: "read", Description: "Read roles"},
	{Key: "role:write", Resource: "role", Action: "write", Description: "Manage roles"},
	{Key: "permission:read", Resource: "permission", Action: "read", Description: "Read permission catalogue and grants"},
	{Key: "permission:write", Resource: "permission", Action: "write", Description: "Replace role permission grants"},
	{Key: "sla:read", Resource: "sla", Action: "read", Description: "Read SLA policies and ticket state"},
	{Key: "sla:write", Resource: "sla", Action: "write", Description: "Manage SLA policies and ticket state"},
	{Key: "webhook:read", Resource: "webhook", Action: "read", Description: "Read webhooks"},
	{Key: "webhook:write", Resource: "webhook", Action: "write", Description: "Manage webhooks"},
	{Key: "credential:read", Resource: "credential", Action: "read", Description: "Read credential metadata"},
	{Key: "credential:write", Resource: "credential", Action: "write", Description: "Manage credentials"},
	{Key: "audit:read", Resource: "audit", Action: "read", Description: "Read audit trails"},
	{Key: "ipam:read", Resource: "ipam", Action: "read", Description: "Read IPAM data"},
	{Key: "ipam:write", Resource: "ipam", Action: "write", Description: "Manage IPAM data"},
	{Key: "rack:read", Resource: "rack", Action: "read", Description: "Read racks"},
	{Key: "rack:write", Resource: "rack", Action: "write", Description: "Manage racks"},
	{Key: "contact:read", Resource: "contact", Action: "read", Description: "Read contacts"},
	{Key: "contact:write", Resource: "contact", Action: "write", Description: "Manage contacts"},
}
