package permission

// Catalogue is the canonical set of permission keys the API exposes today.
var Catalogue = []Permission{
	{Key: "ci:read", Resource: "ci", Action: "read", Description: "Read configuration items"},
	{Key: "ci:write", Resource: "ci", Action: "write", Description: "Create and update configuration items"},
	{Key: "ci:delete", Resource: "ci", Action: "delete", Description: "Delete configuration items"},
	{Key: "topology:read", Resource: "topology", Action: "read", Description: "Read CI topology graphs"},
	{Key: "discovery:read", Resource: "discovery", Action: "read", Description: "Read collectors and discovery jobs"},
	{Key: "asset:read", Resource: "asset", Action: "read", Description: "Read assets"},
	{Key: "asset:write", Resource: "asset", Action: "write", Description: "Manage assets"},
	{Key: "assignment:read", Resource: "assignment", Action: "read", Description: "Read assignments"},
	{Key: "assignment:write", Resource: "assignment", Action: "write", Description: "Manage assignments"},
	{Key: "document:read", Resource: "document", Action: "read", Description: "Read documents"},
	{Key: "document:write", Resource: "document", Action: "write", Description: "Manage documents"},
	{Key: "stocktake:read", Resource: "stocktake", Action: "read", Description: "Read stocktakes"},
	{Key: "stocktake:write", Resource: "stocktake", Action: "write", Description: "Manage stocktakes"},
	{Key: "ticket:read", Resource: "ticket", Action: "read", Description: "Read tickets"},
	{Key: "ticket:write", Resource: "ticket", Action: "write", Description: "Manage tickets and comments"},
	{Key: "user:read", Resource: "user", Action: "read", Description: "Read users and teams"},
	{Key: "user:write", Resource: "user", Action: "write", Description: "Manage users and teams"},
	{Key: "user:manage", Resource: "user", Action: "manage", Description: "Administer users, teams and clients"},
	{Key: "role:read", Resource: "role", Action: "read", Description: "Read roles"},
	{Key: "role:write", Resource: "role", Action: "write", Description: "Manage roles"},
	{Key: "role:manage", Resource: "role", Action: "manage", Description: "Administer roles"},
	{Key: "permission:read", Resource: "permission", Action: "read", Description: "Read permission catalogue and grants"},
	{Key: "permission:write", Resource: "permission", Action: "write", Description: "Replace role permission grants"},
	{Key: "sla:read", Resource: "sla", Action: "read", Description: "Read SLA policies and ticket state"},
	{Key: "sla:write", Resource: "sla", Action: "write", Description: "Manage SLA policies and ticket state"},
	{Key: "webhook:read", Resource: "webhook", Action: "read", Description: "Read webhooks"},
	{Key: "webhook:write", Resource: "webhook", Action: "write", Description: "Manage webhooks"},
	{Key: "webhook:manage", Resource: "webhook", Action: "manage", Description: "Administer webhook subscriptions"},
	{Key: "credential:read", Resource: "credential", Action: "read", Description: "Read credential metadata"},
	{Key: "credential:write", Resource: "credential", Action: "write", Description: "Manage credentials"},
	{Key: "credential:manage", Resource: "credential", Action: "manage", Description: "Administer credentials"},
	{Key: "audit:read", Resource: "audit", Action: "read", Description: "Read audit trails"},
	{Key: "ipam:read", Resource: "ipam", Action: "read", Description: "Read IPAM data"},
	{Key: "ipam:write", Resource: "ipam", Action: "write", Description: "Manage IPAM data"},
	{Key: "rack:read", Resource: "rack", Action: "read", Description: "Read racks"},
	{Key: "rack:write", Resource: "rack", Action: "write", Description: "Manage racks"},
	{Key: "contact:read", Resource: "contact", Action: "read", Description: "Read contacts"},
	{Key: "contact:write", Resource: "contact", Action: "write", Description: "Manage contacts"},
	{Key: "search:read", Resource: "search", Action: "read", Description: "Search configuration items"},
	{Key: "search:write", Resource: "search", Action: "write", Description: "Rebuild tenant search indexes"},
	{Key: "ai:read", Resource: "ai", Action: "read", Description: "Use the AI assistant"},
	{Key: "relationship:read", Resource: "relationship", Action: "read", Description: "Read CI relationships"},
	{Key: "relationship:write", Resource: "relationship", Action: "write", Description: "Manage CI relationships"},
	// RBA-01: location:* replaces site:* of v2 (migration 000081).
	{Key: "location:read", Resource: "location", Action: "read", Description: "Read the location tree: sites, buildings, rooms and racks"},
	{Key: "location:write", Resource: "location", Action: "write", Description: "Manage the location tree"},
	{Key: "discovery:manage", Resource: "discovery", Action: "manage", Description: "Manage discovery scopes and jobs"},
	{Key: "collector:manage", Resource: "collector", Action: "manage", Description: "Manage collectors and enrollment codes"},
	{Key: "vrf:manage", Resource: "vrf", Action: "manage", Description: "Manage VRFs"},
	{Key: "review:resolve", Resource: "review", Action: "resolve", Description: "Resolve review items"},
	{Key: "job:read", Resource: "job", Action: "read", Description: "Read jobs"},
	{Key: "notification:manage", Resource: "notification", Action: "manage", Description: "Manage notification channels"},
	{Key: "team:manage", Resource: "team", Action: "manage", Description: "Manage teams and memberships"},
	{Key: "entitlement:read", Resource: "entitlement", Action: "read", Description: "Read tenant entitlements"},
	{Key: "entitlement:manage", Resource: "entitlement", Action: "manage", Description: "Manage tenant entitlements"},
	{Key: "form:read", Resource: "form", Action: "read", Description: "Read forms and submissions"},
	{Key: "form:write", Resource: "form", Action: "write", Description: "Manage forms and submissions"},
	{Key: "workflow:read", Resource: "workflow", Action: "read", Description: "Read workflow definitions and runs"},
	{Key: "workflow:write", Resource: "workflow", Action: "write", Description: "Manage workflow definitions and runs"},
	{Key: "compliance:read", Resource: "compliance", Action: "read", Description: "Read compliance rules and results"},
	{Key: "compliance:write", Resource: "compliance", Action: "write", Description: "Manage compliance rules"},
	{Key: "monitoring:read", Resource: "monitoring", Action: "read", Description: "Read metrics and alerts"},
	{Key: "monitoring:write", Resource: "monitoring", Action: "write", Description: "Ingest metrics and manage alerts"},
	{Key: "iga:read", Resource: "iga", Action: "read", Description: "Read identity governance data"},
	{Key: "iga:write", Resource: "iga", Action: "write", Description: "Manage identity governance"},
	{Key: "export:run", Resource: "export", Action: "run", Description: "Run data exports"},
	{Key: "discovery:ingest", Resource: "discovery", Action: "ingest", Description: "Ingest collector discovery data"},
	{Key: "citype:manage", Resource: "citype", Action: "manage", Description: "Manage CI types"},
	{Key: "apikey:manage", Resource: "apikey", Action: "manage", Description: "Manage API keys"},
	{Key: "consumable:read", Resource: "consumable", Action: "read", Description: "Read consumable stock"},
	{Key: "consumable:write", Resource: "consumable", Action: "write", Description: "Manage consumable stock"},
	{Key: "order:read", Resource: "order", Action: "read", Description: "Read internal orders"},
	{Key: "order:write", Resource: "order", Action: "write", Description: "Manage internal orders"},
	{Key: "order:approve", Resource: "order", Action: "approve", Description: "Approve internal orders"},
	{Key: "maintenance:read", Resource: "maintenance", Action: "read", Description: "Read maintenance windows"},
	{Key: "maintenance:write", Resource: "maintenance", Action: "write", Description: "Manage maintenance windows and notifications"},
	{Key: "disposal:read", Resource: "disposal", Action: "read", Description: "Read disposal records"},
	{Key: "disposal:write", Resource: "disposal", Action: "write", Description: "Create disposal records"},
	{Key: "key:read", Resource: "key", Action: "read", Description: "Read key items"},
	{Key: "key:write", Resource: "key", Action: "write", Description: "Manage key items and assignments"},
	{Key: "training:read", Resource: "training", Action: "read", Description: "Read trainings and assignments"},
	{Key: "training:write", Resource: "training", Action: "write", Description: "Manage trainings and assignments"},
	{Key: "desk:read", Resource: "desk", Action: "read", Description: "Read desks and bookings"},
	{Key: "desk:write", Resource: "desk", Action: "write", Description: "Manage desks and bookings"},
	{Key: "agent:read", Resource: "agent", Action: "read", Description: "Read endpoint agents"},
	{Key: "agent:manage", Resource: "agent", Action: "manage", Description: "Manage endpoint agents, policies and kill-switch"},
	{Key: "agent:ingest", Resource: "agent", Action: "ingest", Description: "Ingest endpoint agent telemetry"},
	{Key: "security:read", Resource: "security", Action: "read", Description: "Read security findings"},
	{Key: "security:write", Resource: "security", Action: "write", Description: "Manage security findings"},
	// Enterprise CMDB + asset/inventory extension (spec §21).
	{Key: "ci_type:manage", Resource: "ci_type", Action: "manage", Description: "Manage CI types"},
	{Key: "ci_attribute:manage", Resource: "ci_attribute", Action: "manage", Description: "Manage CI attribute definitions"},
	{Key: "ci_instance_attribute:manage", Resource: "ci_instance_attribute", Action: "manage", Description: "Manage CI instance attributes"},
	{Key: "relationship_type:manage", Resource: "relationship_type", Action: "manage", Description: "Manage relationship types"},
	{Key: "asset:assign", Resource: "asset", Action: "assign", Description: "Assign assets to users or teams"},
	{Key: "asset:move", Resource: "asset", Action: "move", Description: "Move assets between locations"},
	{Key: "asset:reserve", Resource: "asset", Action: "reserve", Description: "Reserve assets and inventory items"},
	{Key: "inventory:manage", Resource: "inventory", Action: "manage", Description: "Manage inventory locations and stock"},
	{Key: "lifecycle:manage", Resource: "lifecycle", Action: "manage", Description: "Manage lifecycle definitions and transitions"},
	{Key: "override:write", Resource: "override", Action: "write", Description: "Create and clear manual field overrides"},
	{Key: "saved_view:read", Resource: "saved_view", Action: "read", Description: "Read saved views"},
	{Key: "saved_view:write", Resource: "saved_view", Action: "write", Description: "Manage saved views"},
	// Special actions with their own permission (RBA-06, migration 000072).
	{Key: "credential:decrypt", Resource: "credential", Action: "decrypt", Description: "Decrypt stored credential secrets"},
	{Key: "lifecycle:transition", Resource: "lifecycle", Action: "transition", Description: "Execute lifecycle transitions of CIs and assets"},
	{Key: "reconciliation:manage", Resource: "reconciliation", Action: "manage", Description: "Manage reconciliation settings (source policy)"},
}
