package database

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Session variables (GUCs) WithTenant sets transaction-locally for the RLS
// policies (TEN-04). The names follow the TEN-04 text; package
// tenant/rls uses the same names for the RLS catalog test.
const (
	OrgGUC         = "app.org_id"
	UserGUC        = "app.user_id"
	ClientScopeGUC = "app.client_scope"
	SiteScopeGUC   = "app.site_scope"
	TeamScopeGUC   = "app.team_scope"
)

// noAccessScope is the GUC value of an empty scope set. The policies treat an
// unset or empty scope GUC as "all" (TEN-04: NULL = all clients of the org),
// so an empty set is encoded as the nil UUID, which matches no row: the
// referenced ids are generated by gen_random_uuid() (E-08, fail-closed).
const noAccessScope = "00000000-0000-0000-0000-000000000000"

// ErrIncompleteScope is returned by TenantScope.Validate when the organization
// is missing or a scope dimension was never decided. The zero value of
// TenantScope is always incomplete, so a forgotten scope fails closed.
var ErrIncompleteScope = errors.New("tenant scope is incomplete")

// ScopeSet is one scope dimension (clients, sites or teams) of a TenantScope.
// Its zero value is undecided and rejected by Validate. AllScopes grants the
// whole organization; ScopeIDs restricts to the given ids, and an empty list
// grants nothing (E-08).
type ScopeSet struct {
	decided bool
	all     bool
	ids     []string
}

// AllScopes returns the explicit org-wide marker of a scope dimension: the GUC
// stays empty, which the policies read as NULL = all rows of the organization.
func AllScopes() ScopeSet {
	return ScopeSet{decided: true, all: true}
}

// ScopeIDs restricts a scope dimension to the given ids. Without ids the
// dimension grants no access.
func ScopeIDs(ids ...string) ScopeSet {
	return ScopeSet{decided: true, ids: append([]string(nil), ids...)}
}

// IsAll reports whether the set is the org-wide marker.
func (s ScopeSet) IsAll() bool { return s.all }

// IDs returns a copy of the restricted ids; nil for the org-wide marker.
func (s ScopeSet) IDs() []string { return append([]string(nil), s.ids...) }

func (s ScopeSet) validate(name string) error {
	if !s.decided {
		return fmt.Errorf("%w: %s scope is not set (use AllScopes or ScopeIDs)", ErrIncompleteScope, name)
	}
	for _, id := range s.ids {
		if !isUUID(id) {
			return fmt.Errorf("invalid %s scope id %q: not a UUID", name, id)
		}
	}
	return nil
}

// gucValue renders the set for its GUC. The policies parse the value with
// string_to_array(…, ',')::uuid[] (migration 000033), so the uuid[] of TEN-04
// is transported as a comma-separated list.
func (s ScopeSet) gucValue() string {
	switch {
	case s.all:
		return ""
	case len(s.ids) == 0:
		return noAccessScope
	}
	ids := make([]string, len(s.ids))
	for i, id := range s.ids {
		ids[i] = strings.ToLower(id)
	}
	return strings.Join(ids, ",")
}

// TenantScope is the complete RLS context of one transaction (TEN-04): the
// organization, the acting user and the client, site and team scope.
type TenantScope struct {
	OrgID string
	// UserID is the acting user; empty for system jobs.
	UserID  string
	Clients ScopeSet
	Sites   ScopeSet
	Teams   ScopeSet
}

// OrgWideScope returns the scope of an org-wide principal or of a system job
// iterating one tenant (TEN-06: scopes NULL).
func OrgWideScope(orgID, userID string) TenantScope {
	return TenantScope{
		OrgID:   orgID,
		UserID:  userID,
		Clients: AllScopes(),
		Sites:   AllScopes(),
		Teams:   AllScopes(),
	}
}

// Validate checks that the scope is complete: a valid organization id and a
// decision for every scope dimension. A nil scope is incomplete.
func (s *TenantScope) Validate() error {
	if s == nil || s.OrgID == "" {
		return fmt.Errorf("%w: organization id is required", ErrIncompleteScope)
	}
	if !isUUID(s.OrgID) {
		return fmt.Errorf("invalid organization id %q: not a UUID", s.OrgID)
	}
	if err := s.Clients.validate("client"); err != nil {
		return err
	}
	if err := s.Sites.validate("site"); err != nil {
		return err
	}
	return s.Teams.validate("team")
}

// isUUID accepts exactly the canonical 8-4-4-4-12 hex form that the policies
// cast with ::uuid.
func isUUID(s string) bool {
	if len(s) != 36 {
		return false
	}
	for i, r := range s {
		switch i {
		case 8, 13, 18, 23:
			if r != '-' {
				return false
			}
		default:
			if (r < '0' || r > '9') && (r < 'a' || r > 'f') && (r < 'A' || r > 'F') {
				return false
			}
		}
	}
	return true
}

type tenantScopeKey struct{}

// ContextWithTenantScope attaches the request's tenant scope; the tenant
// middleware sets it from the authenticated principal.
func ContextWithTenantScope(ctx context.Context, s *TenantScope) context.Context {
	return context.WithValue(ctx, tenantScopeKey{}, *s)
}

// TenantScopeFromContext returns the scope attached by ContextWithTenantScope.
func TenantScopeFromContext(ctx context.Context) (TenantScope, bool) {
	s, ok := ctx.Value(tenantScopeKey{}).(TenantScope)
	return s, ok
}

// ErrNoTenantScope is returned by WithRequestTenant when the context carries
// no tenant scope. A repository call outside a request or a system context
// therefore fails closed instead of running org-wide (E-08).
var ErrNoTenantScope = errors.New("no tenant scope in context")

// ErrTenantMismatch is returned by WithRequestTenant when the organization of
// a call differs from the organization of the context's scope.
var ErrTenantMismatch = errors.New("organization does not match the tenant scope")

// WithRequestTenant runs fn through WithTenant with the scope attached to ctx
// (ContextWithTenantScope). Repositories that receive the organization as an
// argument use it so the transaction carries the principal's complete scope;
// orgID must be the scope's organization.
func WithRequestTenant(ctx context.Context, pool *pgxpool.Pool, orgID string, fn func(ctx context.Context, tx pgx.Tx) error) error {
	scope, ok := TenantScopeFromContext(ctx)
	if !ok {
		return ErrNoTenantScope
	}
	if !strings.EqualFold(scope.OrgID, orgID) {
		return fmt.Errorf("%w: %q", ErrTenantMismatch, orgID)
	}
	return WithTenant(ctx, pool, &scope, fn)
}
