-- WP-030 (TEN-06, MGT-01): document storage keys stay inside the organization.
--
-- Keys are generated by the server below org/<organization_id>/ (upload of
-- the content). Accepted besides: '' (no content yet) and the key format of
-- uploads before this migration, documents/<organization_id>/<document id>/.
-- Keys that clients set freely on creation may point at another tenant's
-- object; they are reported and cleared, so the document has no content
-- until it is uploaded again.

DO $$
DECLARE
    cleared INTEGER;
BEGIN
    UPDATE document
       SET storage_key = ''
     WHERE storage_key <> ''
       AND NOT (
           (storage_key LIKE 'org/' || organization_id::text || '/%'
            OR storage_key LIKE 'documents/' || organization_id::text || '/' || id::text || '/%')
           AND position('..' IN storage_key) = 0
       );
    GET DIAGNOSTICS cleared = ROW_COUNT;
    IF cleared > 0 THEN
        RAISE NOTICE 'cleared % document storage keys outside the organization prefix', cleared;
    END IF;
END
$$;

ALTER TABLE document ADD CONSTRAINT document_storage_key_org_prefix CHECK (
    storage_key = ''
    OR ((storage_key LIKE 'org/' || organization_id::text || '/%'
         OR storage_key LIKE 'documents/' || organization_id::text || '/' || id::text || '/%')
        AND position('..' IN storage_key) = 0)
);
