ALTER TABLE IF EXISTS rack DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS room DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS building DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS site DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS client DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS organization DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS rack_isolation ON rack;
DROP POLICY IF EXISTS room_isolation ON room;
DROP POLICY IF EXISTS building_isolation ON building;
DROP POLICY IF EXISTS site_isolation ON site;
DROP POLICY IF EXISTS client_isolation ON client;
DROP POLICY IF EXISTS org_isolation ON organization;

DROP INDEX IF EXISTS idx_rack_room;
DROP INDEX IF EXISTS idx_room_building;
DROP INDEX IF EXISTS idx_building_site;
DROP INDEX IF EXISTS idx_site_client;
DROP INDEX IF EXISTS idx_site_org;
DROP INDEX IF EXISTS idx_client_org;

DROP TABLE IF EXISTS rack;
DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS building;
DROP TABLE IF EXISTS site;
DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS organization;

DROP EXTENSION IF EXISTS "pgcrypto";
