package monitoring

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/DataHub-Chiemgau/Reticora-CMDB/backend/internal/database"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

// PGAlertStore persists alert rules and their evaluation state in
// PostgreSQL. The table is RLS-protected; every statement runs inside a
// tenant-scoped transaction (app.org_id).
type PGAlertStore struct {
	pool *pgxpool.Pool
}

// NewPGAlertStore creates a PostgreSQL-backed alert rule store.
func NewPGAlertStore(pool *pgxpool.Pool) *PGAlertStore {
	return &PGAlertStore{pool: pool}
}

// scanRule maps an alert_rule row onto the domain type.
func scanRule(row pgx.Row) (AlertRule, error) {
	var (
		r        AlertRule
		duration time.Duration
	)
	err := row.Scan(&r.ID, &r.OrgID, &r.Name, &r.MetricName, &r.Condition,
		&r.Threshold, &duration, &r.Severity, &r.Enabled,
		&r.PendingSince, &r.LastFiredAt)
	r.Duration = duration
	return r, err
}

const ruleColumns = `id::text, organization_id::text, name, metric_name, condition, threshold,
	EXTRACT(EPOCH FROM duration) * 1000000000, severity, enabled, pending_since, last_fired_at`

// ListRules returns all rules of the tenant ordered by name.
func (s *PGAlertStore) ListRules(ctx context.Context, orgID string) ([]AlertRule, error) {
	rules := make([]AlertRule, 0)
	err := database.WithRequestTenant(ctx, s.pool, orgID, func(ctx context.Context, tx pgx.Tx) error {
		rows, err := tx.Query(ctx, "SELECT "+ruleColumns+" FROM alert_rule ORDER BY name ASC")
		if err != nil {
			return fmt.Errorf("list alert rules: %w", err)
		}
		defer rows.Close()
		for rows.Next() {
			rule, err := scanRule(rows)
			if err != nil {
				return err
			}
			rules = append(rules, rule)
		}
		return rows.Err()
	})
	return rules, err
}

// CreateRule inserts a rule; the id is generated by the database when empty.
func (s *PGAlertStore) CreateRule(ctx context.Context, rule AlertRule) (AlertRule, error) {
	err := database.WithRequestTenant(ctx, s.pool, rule.OrgID, func(ctx context.Context, tx pgx.Tx) error {
		row := tx.QueryRow(ctx,
			`INSERT INTO alert_rule (organization_id, name, metric_name, condition, threshold, duration, severity, enabled)
			 VALUES ($1, $2, $3, $4, $5, $6::interval, $7, $8)
			 RETURNING `+ruleColumns,
			rule.OrgID, rule.Name, rule.MetricName, rule.Condition,
			rule.Threshold, intervalLiteral(rule.Duration), rule.Severity, rule.Enabled)
		created, err := scanRule(row)
		if err != nil {
			return err
		}
		rule = created
		return nil
	})
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == "23505" {
			return AlertRule{}, fmt.Errorf("alert rule already exists")
		}
		return AlertRule{}, fmt.Errorf("create alert rule: %w", err)
	}
	return rule, nil
}

// UpdateRule applies a partial update to the tenant's rule. Only the fields
// set in the request are changed; the returned rule reflects the stored state.
func (s *PGAlertStore) UpdateRule(ctx context.Context, orgID, id string, req UpdateAlertRuleRequest) (AlertRule, error) {
	var rule AlertRule
	err := database.WithRequestTenant(ctx, s.pool, orgID, func(ctx context.Context, tx pgx.Tx) error {
		// orgID scopes via RLS (set by withTenant); the WHERE clause filters the
		// row by id only, so the nullable COALESCE parameters start at $1.
		row := tx.QueryRow(ctx,
			`UPDATE alert_rule SET
				name = COALESCE($2, name),
				condition = COALESCE($3, condition),
				threshold = COALESCE($4, threshold),
				duration = COALESCE($5::interval, duration),
				severity = COALESCE($6, severity),
				enabled = COALESCE($7, enabled),
				updated_at = now()
			 WHERE id = $1::uuid
			 RETURNING `+ruleColumns,
			id, req.Name, req.Condition, req.Threshold, durationPtrLiteral(req.Duration), req.Severity, req.Enabled)
		var err error
		rule, err = scanRule(row)
		if err == pgx.ErrNoRows {
			return errRuleNotFound
		}
		return err
	})
	if err != nil {
		return AlertRule{}, err
	}
	return rule, nil
}

// errRuleNotFound signals an update against a missing or foreign rule id.
var errRuleNotFound = errors.New("alert rule not found")

// durationPtrLiteral converts an optional Go duration string to the interval
// literal Postgres understands; nil stays NULL so COALESCE keeps the old value.
// An unparsable string also maps to NULL (keeping the old value) rather than
// surfacing a confusing Postgres interval error to a caller that bypassed
// handler-side validation.
func durationPtrLiteral(d *string) any {
	if d == nil {
		return nil
	}
	parsed, err := time.ParseDuration(*d)
	if err != nil {
		return nil
	}
	return intervalLiteral(parsed)
}

// DeleteRule removes the tenant's rule and reports whether it existed.
func (s *PGAlertStore) DeleteRule(ctx context.Context, orgID, id string) (bool, error) {
	deleted := false
	err := database.WithRequestTenant(ctx, s.pool, orgID, func(ctx context.Context, tx pgx.Tx) error {
		tag, err := tx.Exec(ctx, "DELETE FROM alert_rule WHERE id = $1::uuid", id)
		if err != nil {
			return fmt.Errorf("delete alert rule: %w", err)
		}
		deleted = tag.RowsAffected() > 0
		return nil
	})
	return deleted, err
}

// ListEnabled returns every enabled rule across tenants; the evaluator needs
// the system-wide view. It reads with the system flag, which cannot write
// (database.WithSystem); the evaluator changes a rule's state in the rule's
// organization.
func (s *PGAlertStore) ListEnabled(ctx context.Context) ([]AlertRule, error) {
	rules := make([]AlertRule, 0)
	err := database.WithSystem(ctx, s.pool, func(ctx context.Context, tx pgx.Tx) error {
		rows, err := tx.Query(ctx, "SELECT "+ruleColumns+" FROM alert_rule WHERE enabled ORDER BY organization_id, name")
		if err != nil {
			return fmt.Errorf("list enabled alert rules: %w", err)
		}
		defer rows.Close()
		for rows.Next() {
			rule, err := scanRule(rows)
			if err != nil {
				return err
			}
			rules = append(rules, rule)
		}
		return rows.Err()
	})
	if err != nil {
		return nil, err
	}
	return rules, nil
}

// updateRuleState changes the evaluation state of a rule in its
// organization's tenant transaction (org-wide on behalf of the organization,
// E-08).
func (s *PGAlertStore) updateRuleState(ctx context.Context, orgID, ruleID, what, query string, args ...any) error {
	scope := database.OrgWideScope(orgID, "")
	return database.WithTenant(ctx, s.pool, &scope, func(ctx context.Context, tx pgx.Tx) error {
		tag, err := tx.Exec(ctx, query, args...)
		if err != nil {
			return fmt.Errorf("%s: %w", what, err)
		}
		if tag.RowsAffected() == 0 {
			return fmt.Errorf("alert rule %s not found", ruleID)
		}
		return nil
	})
}

// MarkPending records when the condition started being true.
func (s *PGAlertStore) MarkPending(ctx context.Context, rule AlertRule, since time.Time) error {
	return s.updateRuleState(ctx, rule.OrgID, rule.ID, "mark alert rule pending",
		"UPDATE alert_rule SET pending_since = $1 WHERE id = $2::uuid", since.UTC(), rule.ID)
}

// MarkFired records the firing and clears the pending marker.
func (s *PGAlertStore) MarkFired(ctx context.Context, rule AlertRule, at time.Time) error {
	return s.updateRuleState(ctx, rule.OrgID, rule.ID, "mark alert rule fired",
		"UPDATE alert_rule SET pending_since = NULL, last_fired_at = $1 WHERE id = $2::uuid", at.UTC(), rule.ID)
}

// ClearPending resets the duration tracking once the condition no longer
// holds so a later breach starts a fresh duration window.
func (s *PGAlertStore) ClearPending(ctx context.Context, rule AlertRule) error {
	return s.updateRuleState(ctx, rule.OrgID, rule.ID, "clear alert rule pending state",
		"UPDATE alert_rule SET pending_since = NULL WHERE id = $1::uuid", rule.ID)
}

func intervalLiteral(d time.Duration) string {
	return fmt.Sprintf("%f seconds", d.Seconds())
}
